<?php

declare(strict_types=1);

const TTS_DIAGNOSTICS = true;

/* @return int|false
 * number of served bytes of streamed contents
 * false if no contents available
 */
function try_to_stream($localFilePath) {
	$wip = null;
	$openedFilePath = $localFilePath . '.wip';
	$localFile = @fopen($openedFilePath, 'r');
	if ($localFile) {
		$wip = true;
	} else {
		$openedFilePath = $localFilePath;
		$localFile = @fopen($openedFilePath, 'r');
		$wip = false;
	}
	if ($localFile) {
		header("Content-Type: audio/mpeg");
		if (!$wip) {
			header("Cache-Control: private, immutable, max-age=31536000");
			$size = filesize($openedFilePath);
			error_log("filesize($openedFilePath): $size");
			assert($size !== false);
			header("Content-Length: $size");
			$ret = fpassthru($localFile);
			return $ret;
		}

		// We could handle If-Modified-Since header, but we may just not bother and always serve.
		// If $wip is true, it's changing all the time so no way we're returning "304 Not Modified".
		// If $wip is false, we indicate with Cache-Control that it's immutable so we expect there will be no other
		// request.

		// We could handle bytes-range headers but we currently don't.

		header("Cache-Control: no-store");

		$bytes_served = 0;
		$bytes_generated = null;

		while (true) {
			$ret = fseek($localFile, 0, SEEK_END);
			assert($ret === 0);
			$bytes_generated = ftell($localFile);
			//error_log("$openedFilePath size $bytes_generated");
			$ret = fseek($localFile, $bytes_served, SEEK_SET);
			assert($ret === 0);

			if ($bytes_generated > $bytes_served) {

				if (TTS_DIAGNOSTICS) {
					$firstByteServedFilePath = $localFilePath . '.first-byte-served';
					if ($bytes_served === 0 && !file_exists($firstByteServedFilePath)) {
						touch($firstByteServedFilePath);
					}
				}

				$ret = fpassthru($localFile);
				$bytes_served += $ret;
				//error_log("$ret bytes fpassthru()");
			} else {
				// Exit if WIP file was moved and we've served all the contents
				if (!file_exists($openedFilePath) && filesize($localFilePath) === $bytes_served) {
					break;
				}
				usleep(100000);
			}
		}
		return $bytes_served;
	}
	return false;
}

final class FreshExtension_TTS_Controller extends Minz_ActionController {
	public ?Minz_Extension $extension;

	#[\Override]
	public function init(): void {
		$this->extension = Minz_ExtensionManager::findExtension('TTS');
	}

	public function playAction(): void {
		if (!FreshRSS_Context::hasSystemConf()) {
			throw new FreshRSS_Context_Exception('System configuration not initialised!');
		}

		$id = Minz_Request::paramString('id');
		if ($id === '') {
			http_response_code(404);
		}
		$dir = '/tmp/tts_job.' . $id;
		$localFilePath = $dir . '/output.mp3';
		$whoFilePath = $dir . '/who';

		if (FreshRSS_Auth::hasAccess()) {
			$username = Minz_Session::paramString('currentUser');
			assert($username);
			$consumerDescription = "User '$username'";
		} else {
			// TODO if .mp3 file exists, and .who file has the default user's name, and default user's readings are made public
			// TODO even harder: how to make this distinguishable to client javascript without a lot of HTTP requests?
			if (
				FreshRSS_Context::systemConf()->allow_anonymous
				&& file_exists($whoFilePath)
				&& file_get_contents($whoFilePath) === FreshRSS_Context::systemConf()->default_user
			) {
				$consumerDescription = "Anonymous from {$_SERVER['REMOTE_ADDR']}";
			} else {
				http_response_code(403);
				assert(false); // this location is unreachable
				exit(1);
			}
		}

		$ret = try_to_stream($localFilePath);
		if ($ret) {
			error_log("TTS: $consumerDescription, entry id $id. Result: served precached audio, $ret bytes");
			exit(0);
		}

		if (!isset($username)) {
			// This is an anonymous access, but audio hasn't been generated by request from authenticated user.
			// Nothing to serve.
			error_log("TTS: $consumerDescription, entry id $id. Result: no precached audio to serve");
			// TODO serve 204 No Content
			http_response_code(204);
			exit(0);
		}

		$entryDAO = FreshRSS_Factory::createEntryDao();
		$entry = $entryDAO->searchById($id);
		if ($entry === null) {
			http_response_code(404);
			exit(0);
		}
		$entry->loadCompleteContent();
		$htmlContent = $entry->title() . "\n\n" . $entry->content(/*withEnclosures=*/false);
		$contentStrlen = strlen($htmlContent);

		$ret = mkdir($dir);
		if ($ret === false) {
			// directory already exists
			assert(false);
			exit(1);
		}

		$input_html_file = fopen($dir . '/input.html', 'wb');
		fwrite($input_html_file, $htmlContent);
		fclose($input_html_file);

		$tagDAO = FreshRSS_Factory::createTagDao();
		$tag = $tagDAO->searchByName('TTS');
		if ($tag) {
			$tagId = $tag->id();
		} else {
			$tagId = $tagDAO->addTag(['name' => 'TTS']);
		}
		$applyLabels[] = [
			'id_tag' => $tagId,
			'id_entry' => $id,
		];
		$tagDAO->tagEntries($applyLabels);

		/*
		$metadata = array();
		$metadata['entry_id'] = $id;
		$metadata['username'] = $username;
		$metadata_fd = fopen($dir . '/metadata.json', 'wb');
		fwrite(json_encode($metadata), $metadata_fd);
		fclose($metadata_fd);
		*/

		error_log("TTS: $consumerDescription, entry id $id, running TTS on $contentStrlen bytes of text input, $dir");
		file_put_contents($whoFilePath, $username);

		$ttsJobScriptPath = dirname(dirname(__FILE__)) . '/tts_job';
		$cmd = "nohup '$ttsJobScriptPath' '$dir' >/dev/null 2>'$dir/stderr' &";
		$ret = shell_exec($cmd);
		if ($ret !== false && $ret !== null) {
			error_log("TTS: $consumerDescription, entry id $id, running TTS on $contentStrlen bytes of text input, $dir. Result: shell_exec() returned $ret");
			assert(false);
			exit(1);
		}

		$usleepAmount = 100*1000;
		$totalSlept = 0;
		while ($totalSlept < 30*1000*1000) {
			$ret = try_to_stream($localFilePath);
			if ($ret) {
				error_log("TTS: $consumerDescription, entry id $id, running TTS on $contentStrlen bytes of text input, $dir. Result: served generated audio, $ret bytes");
				exit(0);
			}
			usleep($usleepAmount);
			$totalSlept += $usleepAmount;
			$usleepAmount *= 2;
		}
		// We should have successfully started streaming and exited.
		// Streaming failed if we're here.
		error_log("TTS: $consumerDescription, entry id $id, running TTS on $contentStrlen bytes of text input, $dir. Result: failed to serve");
		assert(false);
		exit(1);
		// don't try to load any view
	}
}
