<?php
	declare(strict_types=1);
	/** @var CustomJSExtension $this */
?>
<form action="<?= _url('extension', 'configure', 'e', urlencode($this->getName())) ?>" method="post">
	<input type="hidden" name="_csrf" value="<?= FreshRSS_Auth::csrfToken() ?>" />
	<div class="form-group">
		<label class="group-name" for="words_primary"><?= _t('ext.highlightwords.words_primary') ?></label>
		<div class="group-controls">
			<textarea name="words_primary" id="words_primary"><?= $this->words_primary ?></textarea>
		</div>
	</div>
	
	<div class="form-group">
		<label class="group-name" for="words_secondary"><?= _t('ext.highlightwords.words_secondary') ?></label>
		<div class="group-controls">
			<textarea name="words_secondary" id="words_secondary"><?= $this->words_secondary ?></textarea>
		</div>
	</div>

	<div class="form-group">
		<label class="group-name" for="enableInArticle"></label>
		<div class="group-controls">
			<label><input id="enableInArticle" name="enableInArticle" type="checkbox" <?= $this->enableInArticle === 'true' ? 'checked' : '' ?> /><?= _t('ext.highlightwords.enableInArticle') ?></label>
		</div>
	</div>

	<div class="form-group form-actions">
		<?php if ($this->permission_problem !== '') { ?>
			<p class="alert alert-error"><?= _t('ext.highlightwords.permission_problem', $this->permission_problem) ?></p>
		<?php } else { ?>
			<div class="group-controls">
				<button type="submit" class="btn btn-important"><?= _t('gen.action.submit') ?></button>
				<button type="reset" class="btn"><?= _t('gen.action.cancel') ?></button>
			</div>
		<?php } ?>
	</div>
</form>
